#############################################################################
# Makefile for building: bin/ocelot
# Generated by qmake (3.1) (Qt 5.14.0)
# Project:  ocelot.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ocelot.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -pthread -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -pthread -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/taglib -isystem /usr/include/Qt5GStreamer -isystem /usr/include/qt/QtCore -isystem /usr/include/qt -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/orc-0.4 -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtNetwork -I/tmp/ocelotbuild -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ocelot1.0.0
DISTDIR = /tmp/ocelotbuild/ocelot1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -ltag -lQt5GStreamer-1.0 -lQt5GLib-2.0 -lQt5Core /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Sql.so /usr/lib/libQt5DBus.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lGL -lpthread -lmd4c   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = /tmp/ocelotbuild/

####### Files

SOURCES       = src/_main.cpp \
		src/gui/cwidgets/coverview.cpp \
		src/gui/cwidgets/dummywidget.cpp \
		src/gui/cwidgets/libtree.cpp \
		src/gui/cwidgets/playlist.cpp \
		src/gui/cwidgets/playlistview.cpp \
		src/gui/cwidgets/progslider.cpp \
		src/gui/cwidgets/splitter.cpp \
		src/gui/cwidgets/tabbutton.cpp \
		src/gui/cwidgets/tagview.cpp \
		src/gui/cwidgets/toolbar.cpp \
		src/gui/cwidgets/visualizer.cpp \
		src/gui/cwidgets/volslider.cpp \
		src/gui/dialogs/about.cpp \
		src/gui/dialogs/settings.cpp \
		src/gui/dialogs/tageditor.cpp \
		src/gui/dialogs/transchelper.cpp \
		src/gui/dialogs/transcoder.cpp \
		src/gui/dialogs/wizard.cpp \
		src/gui/helpers/flachelper.cpp \
		src/gui/helpers/intro.cpp \
		src/gui/mwindow.cpp \
		src/gui/workbench.cpp \
		src/library.cpp \
		src/libs/QSingleInstance/clientinstance.cpp \
		src/libs/QSingleInstance/qsingleinstance.cpp \
		src/libs/QSingleInstance/qsingleinstance_p.cpp \
		src/libs/libnotify-qt/Notification.cpp \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp \
		src/player.cpp \
		src/trackdata.cpp \
		src/utils/topostfix.cpp \
		src/vars.cpp qrc_package.cpp \
		/tmp/ocelotbuild/moc_coverview.cpp \
		/tmp/ocelotbuild/moc_dummywidget.cpp \
		/tmp/ocelotbuild/moc_libtree.cpp \
		/tmp/ocelotbuild/moc_playlist.cpp \
		/tmp/ocelotbuild/moc_playlistview.cpp \
		/tmp/ocelotbuild/moc_splitter.cpp \
		/tmp/ocelotbuild/moc_tabbutton.cpp \
		/tmp/ocelotbuild/moc_tagview.cpp \
		/tmp/ocelotbuild/moc_toolbar.cpp \
		/tmp/ocelotbuild/moc_transchelper.cpp \
		/tmp/ocelotbuild/moc_transcoder.cpp \
		/tmp/ocelotbuild/moc_wizard.cpp \
		/tmp/ocelotbuild/moc_flachelper.cpp \
		/tmp/ocelotbuild/moc_intro.cpp \
		/tmp/ocelotbuild/moc_mwindow.cpp \
		/tmp/ocelotbuild/moc_library.cpp \
		/tmp/ocelotbuild/moc_clientinstance.cpp \
		/tmp/ocelotbuild/moc_qsingleinstance.cpp \
		/tmp/ocelotbuild/moc_qsingleinstance_p.cpp \
		/tmp/ocelotbuild/moc_Notification.cpp \
		/tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp \
		/tmp/ocelotbuild/moc_player.cpp \
		/tmp/ocelotbuild/moc_vars.cpp
OBJECTS       = /tmp/ocelotbuild/_main.o \
		/tmp/ocelotbuild/coverview.o \
		/tmp/ocelotbuild/dummywidget.o \
		/tmp/ocelotbuild/libtree.o \
		/tmp/ocelotbuild/playlist.o \
		/tmp/ocelotbuild/playlistview.o \
		/tmp/ocelotbuild/progslider.o \
		/tmp/ocelotbuild/splitter.o \
		/tmp/ocelotbuild/tabbutton.o \
		/tmp/ocelotbuild/tagview.o \
		/tmp/ocelotbuild/toolbar.o \
		/tmp/ocelotbuild/visualizer.o \
		/tmp/ocelotbuild/volslider.o \
		/tmp/ocelotbuild/about.o \
		/tmp/ocelotbuild/settings.o \
		/tmp/ocelotbuild/tageditor.o \
		/tmp/ocelotbuild/transchelper.o \
		/tmp/ocelotbuild/transcoder.o \
		/tmp/ocelotbuild/wizard.o \
		/tmp/ocelotbuild/flachelper.o \
		/tmp/ocelotbuild/intro.o \
		/tmp/ocelotbuild/mwindow.o \
		/tmp/ocelotbuild/workbench.o \
		/tmp/ocelotbuild/library.o \
		/tmp/ocelotbuild/clientinstance.o \
		/tmp/ocelotbuild/qsingleinstance.o \
		/tmp/ocelotbuild/qsingleinstance_p.o \
		/tmp/ocelotbuild/Notification.o \
		/tmp/ocelotbuild/OrgFreedesktopNotificationsInterface.o \
		/tmp/ocelotbuild/player.o \
		/tmp/ocelotbuild/trackdata.o \
		/tmp/ocelotbuild/topostfix.o \
		/tmp/ocelotbuild/vars.o \
		/tmp/ocelotbuild/qrc_package.o \
		/tmp/ocelotbuild/moc_coverview.o \
		/tmp/ocelotbuild/moc_dummywidget.o \
		/tmp/ocelotbuild/moc_libtree.o \
		/tmp/ocelotbuild/moc_playlist.o \
		/tmp/ocelotbuild/moc_playlistview.o \
		/tmp/ocelotbuild/moc_splitter.o \
		/tmp/ocelotbuild/moc_tabbutton.o \
		/tmp/ocelotbuild/moc_tagview.o \
		/tmp/ocelotbuild/moc_toolbar.o \
		/tmp/ocelotbuild/moc_transchelper.o \
		/tmp/ocelotbuild/moc_transcoder.o \
		/tmp/ocelotbuild/moc_wizard.o \
		/tmp/ocelotbuild/moc_flachelper.o \
		/tmp/ocelotbuild/moc_intro.o \
		/tmp/ocelotbuild/moc_mwindow.o \
		/tmp/ocelotbuild/moc_library.o \
		/tmp/ocelotbuild/moc_clientinstance.o \
		/tmp/ocelotbuild/moc_qsingleinstance.o \
		/tmp/ocelotbuild/moc_qsingleinstance_p.o \
		/tmp/ocelotbuild/moc_Notification.o \
		/tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.o \
		/tmp/ocelotbuild/moc_player.o \
		/tmp/ocelotbuild/moc_vars.o
DIST          = LICENSE \
		README.md \
		README.md \
		/ \
		src/libs/QSingleInstance/LICENSE \
		src/libs/libnotify-qt/LICENSE \
		uncrustify.cfg \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		ocelot.pro src/gui/cwidgets/coverview.hpp \
		src/gui/cwidgets/dummywidget.hpp \
		src/gui/cwidgets/libtree.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/playlistview.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/splitter.hpp \
		src/gui/cwidgets/tabbutton.hpp \
		src/gui/cwidgets/tagview.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/visualizer.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/wizard.hpp \
		src/gui/helpers/flachelper.hpp \
		src/gui/helpers/intro.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/libs/QSingleInstance/clientinstance.h \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/libs/QSingleInstance/qsingleinstance_p.h \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/player.hpp \
		src/trackdata.hpp \
		src/utils/topostfix.hpp \
		src/vars.hpp src/_main.cpp \
		src/gui/cwidgets/coverview.cpp \
		src/gui/cwidgets/dummywidget.cpp \
		src/gui/cwidgets/libtree.cpp \
		src/gui/cwidgets/playlist.cpp \
		src/gui/cwidgets/playlistview.cpp \
		src/gui/cwidgets/progslider.cpp \
		src/gui/cwidgets/splitter.cpp \
		src/gui/cwidgets/tabbutton.cpp \
		src/gui/cwidgets/tagview.cpp \
		src/gui/cwidgets/toolbar.cpp \
		src/gui/cwidgets/visualizer.cpp \
		src/gui/cwidgets/volslider.cpp \
		src/gui/dialogs/about.cpp \
		src/gui/dialogs/settings.cpp \
		src/gui/dialogs/tageditor.cpp \
		src/gui/dialogs/transchelper.cpp \
		src/gui/dialogs/transcoder.cpp \
		src/gui/dialogs/wizard.cpp \
		src/gui/helpers/flachelper.cpp \
		src/gui/helpers/intro.cpp \
		src/gui/mwindow.cpp \
		src/gui/workbench.cpp \
		src/library.cpp \
		src/libs/QSingleInstance/clientinstance.cpp \
		src/libs/QSingleInstance/qsingleinstance.cpp \
		src/libs/QSingleInstance/qsingleinstance_p.cpp \
		src/libs/libnotify-qt/Notification.cpp \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp \
		src/player.cpp \
		src/trackdata.cpp \
		src/utils/topostfix.cpp \
		src/vars.cpp
QMAKE_TARGET  = ocelot
DESTDIR       = bin/
TARGET        = bin/ocelot


first: all
####### Build rules

bin/ocelot:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ocelot.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		ocelot.pro \
		res/package.qrc \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile ocelot.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt/mkspecs/features/qml_debug.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/dbuscommon.pri:
/usr/lib/qt/mkspecs/features/dbusinterfaces.prf:
/usr/lib/qt/mkspecs/features/dbusadaptors.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
ocelot.pro:
res/package.qrc:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ocelot.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile bin/ocelot

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/package.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/cwidgets/coverview.hpp src/gui/cwidgets/dummywidget.hpp src/gui/cwidgets/libtree.hpp src/gui/cwidgets/playlist.hpp src/gui/cwidgets/playlistview.hpp src/gui/cwidgets/progslider.hpp src/gui/cwidgets/splitter.hpp src/gui/cwidgets/tabbutton.hpp src/gui/cwidgets/tagview.hpp src/gui/cwidgets/toolbar.hpp src/gui/cwidgets/visualizer.hpp src/gui/cwidgets/volslider.hpp src/gui/dialogs/about.hpp src/gui/dialogs/settings.hpp src/gui/dialogs/tageditor.hpp src/gui/dialogs/transchelper.hpp src/gui/dialogs/transcoder.hpp src/gui/dialogs/wizard.hpp src/gui/helpers/flachelper.hpp src/gui/helpers/intro.hpp src/gui/mwindow.hpp src/gui/workbench.hpp src/library.hpp src/libs/QSingleInstance/clientinstance.h src/libs/QSingleInstance/qsingleinstance.h src/libs/QSingleInstance/qsingleinstance_p.h src/libs/libnotify-qt/Notification.h src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h src/player.hpp src/trackdata.hpp src/utils/topostfix.hpp src/vars.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/_main.cpp src/gui/cwidgets/coverview.cpp src/gui/cwidgets/dummywidget.cpp src/gui/cwidgets/libtree.cpp src/gui/cwidgets/playlist.cpp src/gui/cwidgets/playlistview.cpp src/gui/cwidgets/progslider.cpp src/gui/cwidgets/splitter.cpp src/gui/cwidgets/tabbutton.cpp src/gui/cwidgets/tagview.cpp src/gui/cwidgets/toolbar.cpp src/gui/cwidgets/visualizer.cpp src/gui/cwidgets/volslider.cpp src/gui/dialogs/about.cpp src/gui/dialogs/settings.cpp src/gui/dialogs/tageditor.cpp src/gui/dialogs/transchelper.cpp src/gui/dialogs/transcoder.cpp src/gui/dialogs/wizard.cpp src/gui/helpers/flachelper.cpp src/gui/helpers/intro.cpp src/gui/mwindow.cpp src/gui/workbench.cpp src/library.cpp src/libs/QSingleInstance/clientinstance.cpp src/libs/QSingleInstance/qsingleinstance.cpp src/libs/QSingleInstance/qsingleinstance_p.cpp src/libs/libnotify-qt/Notification.cpp src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp src/player.cpp src/trackdata.cpp src/utils/topostfix.cpp src/vars.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_package.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_package.cpp
qrc_package.cpp: res/package.qrc \
		/usr/bin/rcc \
		res/pause.svg \
		res/next.svg \
		res/previous.svg \
		res/wrench.png \
		res/start.svg \
		res/stop.svg \
		res/cog.svg \
		res/tapeicon.png \
		res/caticon.png
	/usr/bin/rcc -name package res/package.qrc -o qrc_package.cpp

compiler_moc_predefs_make_all: /tmp/ocelotbuild/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) /tmp/ocelotbuild/moc_predefs.h
/tmp/ocelotbuild/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -pthread -Wall -Wextra -dM -E -o /tmp/ocelotbuild/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: /tmp/ocelotbuild/moc_coverview.cpp /tmp/ocelotbuild/moc_dummywidget.cpp /tmp/ocelotbuild/moc_libtree.cpp /tmp/ocelotbuild/moc_playlist.cpp /tmp/ocelotbuild/moc_playlistview.cpp /tmp/ocelotbuild/moc_splitter.cpp /tmp/ocelotbuild/moc_tabbutton.cpp /tmp/ocelotbuild/moc_tagview.cpp /tmp/ocelotbuild/moc_toolbar.cpp /tmp/ocelotbuild/moc_transchelper.cpp /tmp/ocelotbuild/moc_transcoder.cpp /tmp/ocelotbuild/moc_wizard.cpp /tmp/ocelotbuild/moc_flachelper.cpp /tmp/ocelotbuild/moc_intro.cpp /tmp/ocelotbuild/moc_mwindow.cpp /tmp/ocelotbuild/moc_library.cpp /tmp/ocelotbuild/moc_clientinstance.cpp /tmp/ocelotbuild/moc_qsingleinstance.cpp /tmp/ocelotbuild/moc_qsingleinstance_p.cpp /tmp/ocelotbuild/moc_Notification.cpp /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp /tmp/ocelotbuild/moc_player.cpp /tmp/ocelotbuild/moc_vars.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) /tmp/ocelotbuild/moc_coverview.cpp /tmp/ocelotbuild/moc_dummywidget.cpp /tmp/ocelotbuild/moc_libtree.cpp /tmp/ocelotbuild/moc_playlist.cpp /tmp/ocelotbuild/moc_playlistview.cpp /tmp/ocelotbuild/moc_splitter.cpp /tmp/ocelotbuild/moc_tabbutton.cpp /tmp/ocelotbuild/moc_tagview.cpp /tmp/ocelotbuild/moc_toolbar.cpp /tmp/ocelotbuild/moc_transchelper.cpp /tmp/ocelotbuild/moc_transcoder.cpp /tmp/ocelotbuild/moc_wizard.cpp /tmp/ocelotbuild/moc_flachelper.cpp /tmp/ocelotbuild/moc_intro.cpp /tmp/ocelotbuild/moc_mwindow.cpp /tmp/ocelotbuild/moc_library.cpp /tmp/ocelotbuild/moc_clientinstance.cpp /tmp/ocelotbuild/moc_qsingleinstance.cpp /tmp/ocelotbuild/moc_qsingleinstance_p.cpp /tmp/ocelotbuild/moc_Notification.cpp /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp /tmp/ocelotbuild/moc_player.cpp /tmp/ocelotbuild/moc_vars.cpp
/tmp/ocelotbuild/moc_coverview.cpp: src/gui/cwidgets/coverview.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/coverview.hpp -o /tmp/ocelotbuild/moc_coverview.cpp

/tmp/ocelotbuild/moc_dummywidget.cpp: src/gui/cwidgets/dummywidget.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/dummywidget.hpp -o /tmp/ocelotbuild/moc_dummywidget.cpp

/tmp/ocelotbuild/moc_libtree.cpp: src/gui/cwidgets/libtree.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/libtree.hpp -o /tmp/ocelotbuild/moc_libtree.cpp

/tmp/ocelotbuild/moc_playlist.cpp: src/gui/cwidgets/playlist.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/playlist.hpp -o /tmp/ocelotbuild/moc_playlist.cpp

/tmp/ocelotbuild/moc_playlistview.cpp: src/gui/cwidgets/playlistview.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlist.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/playlistview.hpp -o /tmp/ocelotbuild/moc_playlistview.cpp

/tmp/ocelotbuild/moc_splitter.cpp: src/gui/cwidgets/splitter.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/splitter.hpp -o /tmp/ocelotbuild/moc_splitter.cpp

/tmp/ocelotbuild/moc_tabbutton.cpp: src/gui/cwidgets/tabbutton.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/tabbutton.hpp -o /tmp/ocelotbuild/moc_tabbutton.cpp

/tmp/ocelotbuild/moc_tagview.cpp: src/gui/cwidgets/tagview.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/tagview.hpp -o /tmp/ocelotbuild/moc_tagview.cpp

/tmp/ocelotbuild/moc_toolbar.cpp: src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/player.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/vars.hpp \
		src/library.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/toolbar.hpp -o /tmp/ocelotbuild/moc_toolbar.cpp

/tmp/ocelotbuild/moc_transchelper.cpp: src/gui/dialogs/transchelper.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/transchelper.hpp -o /tmp/ocelotbuild/moc_transchelper.cpp

/tmp/ocelotbuild/moc_transcoder.cpp: src/gui/dialogs/transcoder.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/dialogs/transchelper.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/transcoder.hpp -o /tmp/ocelotbuild/moc_transcoder.cpp

/tmp/ocelotbuild/moc_wizard.cpp: src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/wizard.hpp -o /tmp/ocelotbuild/moc_wizard.cpp

/tmp/ocelotbuild/moc_flachelper.cpp: src/gui/helpers/flachelper.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/helpers/flachelper.hpp -o /tmp/ocelotbuild/moc_flachelper.cpp

/tmp/ocelotbuild/moc_intro.cpp: src/gui/helpers/intro.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/helpers/intro.hpp -o /tmp/ocelotbuild/moc_intro.cpp

/tmp/ocelotbuild/moc_mwindow.cpp: src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/mwindow.hpp -o /tmp/ocelotbuild/moc_mwindow.cpp

/tmp/ocelotbuild/moc_library.cpp: src/library.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/library.hpp -o /tmp/ocelotbuild/moc_library.cpp

/tmp/ocelotbuild/moc_clientinstance.cpp: src/libs/QSingleInstance/clientinstance.h \
		src/libs/QSingleInstance/qsingleinstance_p.h \
		src/libs/QSingleInstance/qsingleinstance.h \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/QSingleInstance/clientinstance.h -o /tmp/ocelotbuild/moc_clientinstance.cpp

/tmp/ocelotbuild/moc_qsingleinstance.cpp: src/libs/QSingleInstance/qsingleinstance.h \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/QSingleInstance/qsingleinstance.h -o /tmp/ocelotbuild/moc_qsingleinstance.cpp

/tmp/ocelotbuild/moc_qsingleinstance_p.cpp: src/libs/QSingleInstance/qsingleinstance_p.h \
		src/libs/QSingleInstance/qsingleinstance.h \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/QSingleInstance/qsingleinstance_p.h -o /tmp/ocelotbuild/moc_qsingleinstance_p.cpp

/tmp/ocelotbuild/moc_Notification.cpp: src/libs/libnotify-qt/Notification.h \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/libnotify-qt/Notification.h -o /tmp/ocelotbuild/moc_Notification.cpp

/tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp: src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h -o /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp

/tmp/ocelotbuild/moc_player.cpp: src/player.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/player.hpp -o /tmp/ocelotbuild/moc_player.cpp

/tmp/ocelotbuild/moc_vars.cpp: src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		/tmp/ocelotbuild/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /tmp/ocelotbuild/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/matheus/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/qt/QtNetwork -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/vars.hpp -o /tmp/ocelotbuild/moc_vars.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

/tmp/ocelotbuild/_main.o: src/_main.cpp src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/_main.o src/_main.cpp

/tmp/ocelotbuild/coverview.o: src/gui/cwidgets/coverview.cpp src/gui/cwidgets/coverview.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/coverview.o src/gui/cwidgets/coverview.cpp

/tmp/ocelotbuild/dummywidget.o: src/gui/cwidgets/dummywidget.cpp src/gui/cwidgets/dummywidget.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/dummywidget.o src/gui/cwidgets/dummywidget.cpp

/tmp/ocelotbuild/libtree.o: src/gui/cwidgets/libtree.cpp src/gui/cwidgets/libtree.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/libtree.o src/gui/cwidgets/libtree.cpp

/tmp/ocelotbuild/playlist.o: src/gui/cwidgets/playlist.cpp src/gui/cwidgets/playlist.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlistview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/playlist.o src/gui/cwidgets/playlist.cpp

/tmp/ocelotbuild/playlistview.o: src/gui/cwidgets/playlistview.cpp src/gui/cwidgets/playlistview.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/tabbutton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/playlistview.o src/gui/cwidgets/playlistview.cpp

/tmp/ocelotbuild/progslider.o: src/gui/cwidgets/progslider.cpp src/gui/cwidgets/progslider.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/progslider.o src/gui/cwidgets/progslider.cpp

/tmp/ocelotbuild/splitter.o: src/gui/cwidgets/splitter.cpp src/gui/cwidgets/splitter.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/splitter.o src/gui/cwidgets/splitter.cpp

/tmp/ocelotbuild/tabbutton.o: src/gui/cwidgets/tabbutton.cpp src/gui/cwidgets/tabbutton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/tabbutton.o src/gui/cwidgets/tabbutton.cpp

/tmp/ocelotbuild/tagview.o: src/gui/cwidgets/tagview.cpp src/gui/cwidgets/tagview.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/tagview.o src/gui/cwidgets/tagview.cpp

/tmp/ocelotbuild/toolbar.o: src/gui/cwidgets/toolbar.cpp src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/player.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/splitter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/toolbar.o src/gui/cwidgets/toolbar.cpp

/tmp/ocelotbuild/visualizer.o: src/gui/cwidgets/visualizer.cpp src/gui/cwidgets/visualizer.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/visualizer.o src/gui/cwidgets/visualizer.cpp

/tmp/ocelotbuild/volslider.o: src/gui/cwidgets/volslider.cpp src/gui/cwidgets/volslider.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/progslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/volslider.o src/gui/cwidgets/volslider.cpp

/tmp/ocelotbuild/about.o: src/gui/dialogs/about.cpp src/gui/dialogs/about.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/about.o src/gui/dialogs/about.cpp

/tmp/ocelotbuild/settings.o: src/gui/dialogs/settings.cpp src/gui/dialogs/settings.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/settings.o src/gui/dialogs/settings.cpp

/tmp/ocelotbuild/tageditor.o: src/gui/dialogs/tageditor.cpp src/gui/dialogs/tageditor.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/tageditor.o src/gui/dialogs/tageditor.cpp

/tmp/ocelotbuild/transchelper.o: src/gui/dialogs/transchelper.cpp src/gui/dialogs/transchelper.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/helpers/flachelper.hpp \
		src/gui/helpers/intro.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/transchelper.o src/gui/dialogs/transchelper.cpp

/tmp/ocelotbuild/transcoder.o: src/gui/dialogs/transcoder.cpp src/gui/dialogs/transcoder.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/transcoder.o src/gui/dialogs/transcoder.cpp

/tmp/ocelotbuild/wizard.o: src/gui/dialogs/wizard.cpp src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/wizard.o src/gui/dialogs/wizard.cpp

/tmp/ocelotbuild/flachelper.o: src/gui/helpers/flachelper.cpp src/gui/helpers/flachelper.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/flachelper.o src/gui/helpers/flachelper.cpp

/tmp/ocelotbuild/intro.o: src/gui/helpers/intro.cpp src/gui/helpers/intro.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/intro.o src/gui/helpers/intro.cpp

/tmp/ocelotbuild/mwindow.o: src/gui/mwindow.cpp src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/libs/libnotify-qt/Notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/mwindow.o src/gui/mwindow.cpp

/tmp/ocelotbuild/workbench.o: src/gui/workbench.cpp src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/utils/topostfix.hpp \
		src/gui/mwindow.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/coverview.hpp \
		src/gui/cwidgets/dummywidget.hpp \
		src/gui/cwidgets/libtree.hpp \
		src/gui/cwidgets/playlistview.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/splitter.hpp \
		src/gui/cwidgets/tagview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/workbench.o src/gui/workbench.cpp

/tmp/ocelotbuild/library.o: src/library.cpp src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/library.o src/library.cpp

/tmp/ocelotbuild/clientinstance.o: src/libs/QSingleInstance/clientinstance.cpp src/libs/QSingleInstance/clientinstance.h \
		src/libs/QSingleInstance/qsingleinstance_p.h \
		src/libs/QSingleInstance/qsingleinstance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/clientinstance.o src/libs/QSingleInstance/clientinstance.cpp

/tmp/ocelotbuild/qsingleinstance.o: src/libs/QSingleInstance/qsingleinstance.cpp src/libs/QSingleInstance/qsingleinstance.h \
		src/libs/QSingleInstance/qsingleinstance_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/qsingleinstance.o src/libs/QSingleInstance/qsingleinstance.cpp

/tmp/ocelotbuild/qsingleinstance_p.o: src/libs/QSingleInstance/qsingleinstance_p.cpp src/libs/QSingleInstance/qsingleinstance_p.h \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/libs/QSingleInstance/clientinstance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/qsingleinstance_p.o src/libs/QSingleInstance/qsingleinstance_p.cpp

/tmp/ocelotbuild/Notification.o: src/libs/libnotify-qt/Notification.cpp src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/Notification.o src/libs/libnotify-qt/Notification.cpp

/tmp/ocelotbuild/OrgFreedesktopNotificationsInterface.o: src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/OrgFreedesktopNotificationsInterface.o src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp

/tmp/ocelotbuild/player.o: src/player.cpp src/player.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/libs/QSingleInstance/qsingleinstance.h \
		src/trackdata.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/player.o src/player.cpp

/tmp/ocelotbuild/trackdata.o: src/trackdata.cpp src/trackdata.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/trackdata.o src/trackdata.cpp

/tmp/ocelotbuild/topostfix.o: src/utils/topostfix.cpp src/utils/topostfix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/topostfix.o src/utils/topostfix.cpp

/tmp/ocelotbuild/vars.o: src/vars.cpp src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/vars.o src/vars.cpp

/tmp/ocelotbuild/qrc_package.o: qrc_package.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/qrc_package.o qrc_package.cpp

/tmp/ocelotbuild/moc_coverview.o: /tmp/ocelotbuild/moc_coverview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_coverview.o /tmp/ocelotbuild/moc_coverview.cpp

/tmp/ocelotbuild/moc_dummywidget.o: /tmp/ocelotbuild/moc_dummywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_dummywidget.o /tmp/ocelotbuild/moc_dummywidget.cpp

/tmp/ocelotbuild/moc_libtree.o: /tmp/ocelotbuild/moc_libtree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_libtree.o /tmp/ocelotbuild/moc_libtree.cpp

/tmp/ocelotbuild/moc_playlist.o: /tmp/ocelotbuild/moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_playlist.o /tmp/ocelotbuild/moc_playlist.cpp

/tmp/ocelotbuild/moc_playlistview.o: /tmp/ocelotbuild/moc_playlistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_playlistview.o /tmp/ocelotbuild/moc_playlistview.cpp

/tmp/ocelotbuild/moc_splitter.o: /tmp/ocelotbuild/moc_splitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_splitter.o /tmp/ocelotbuild/moc_splitter.cpp

/tmp/ocelotbuild/moc_tabbutton.o: /tmp/ocelotbuild/moc_tabbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_tabbutton.o /tmp/ocelotbuild/moc_tabbutton.cpp

/tmp/ocelotbuild/moc_tagview.o: /tmp/ocelotbuild/moc_tagview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_tagview.o /tmp/ocelotbuild/moc_tagview.cpp

/tmp/ocelotbuild/moc_toolbar.o: /tmp/ocelotbuild/moc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_toolbar.o /tmp/ocelotbuild/moc_toolbar.cpp

/tmp/ocelotbuild/moc_transchelper.o: /tmp/ocelotbuild/moc_transchelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_transchelper.o /tmp/ocelotbuild/moc_transchelper.cpp

/tmp/ocelotbuild/moc_transcoder.o: /tmp/ocelotbuild/moc_transcoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_transcoder.o /tmp/ocelotbuild/moc_transcoder.cpp

/tmp/ocelotbuild/moc_wizard.o: /tmp/ocelotbuild/moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_wizard.o /tmp/ocelotbuild/moc_wizard.cpp

/tmp/ocelotbuild/moc_flachelper.o: /tmp/ocelotbuild/moc_flachelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_flachelper.o /tmp/ocelotbuild/moc_flachelper.cpp

/tmp/ocelotbuild/moc_intro.o: /tmp/ocelotbuild/moc_intro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_intro.o /tmp/ocelotbuild/moc_intro.cpp

/tmp/ocelotbuild/moc_mwindow.o: /tmp/ocelotbuild/moc_mwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_mwindow.o /tmp/ocelotbuild/moc_mwindow.cpp

/tmp/ocelotbuild/moc_library.o: /tmp/ocelotbuild/moc_library.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_library.o /tmp/ocelotbuild/moc_library.cpp

/tmp/ocelotbuild/moc_clientinstance.o: /tmp/ocelotbuild/moc_clientinstance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_clientinstance.o /tmp/ocelotbuild/moc_clientinstance.cpp

/tmp/ocelotbuild/moc_qsingleinstance.o: /tmp/ocelotbuild/moc_qsingleinstance.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_qsingleinstance.o /tmp/ocelotbuild/moc_qsingleinstance.cpp

/tmp/ocelotbuild/moc_qsingleinstance_p.o: /tmp/ocelotbuild/moc_qsingleinstance_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_qsingleinstance_p.o /tmp/ocelotbuild/moc_qsingleinstance_p.cpp

/tmp/ocelotbuild/moc_Notification.o: /tmp/ocelotbuild/moc_Notification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_Notification.o /tmp/ocelotbuild/moc_Notification.cpp

/tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.o: /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.o /tmp/ocelotbuild/moc_OrgFreedesktopNotificationsInterface.cpp

/tmp/ocelotbuild/moc_player.o: /tmp/ocelotbuild/moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_player.o /tmp/ocelotbuild/moc_player.cpp

/tmp/ocelotbuild/moc_vars.o: /tmp/ocelotbuild/moc_vars.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/ocelotbuild/moc_vars.o /tmp/ocelotbuild/moc_vars.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

