#############################################################################
# Makefile for building: bin/ocelot
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  ocelot.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ocelot.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/taglib -isystem /usr/include/Qt5GStreamer -isystem /usr/include/qt/QtCore -isystem /usr/include/qt -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/orc-0.4 -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtDBus -Iobj -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-clang
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ocelot1.0.0
DISTDIR = /home/user/devel/projects/ocelot/obj/ocelot1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS) -ltag -lQt5GStreamer-1.0 -lQt5GLib-2.0 -lQt5Core /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Sql.so /usr/lib/libQt5DBus.so /usr/lib/libQt5Core.so /usr/lib/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/_main.cpp \
		src/gui/cwidgets/coverview.cpp \
		src/gui/cwidgets/dummywidget.cpp \
		src/gui/cwidgets/libtree.cpp \
		src/gui/cwidgets/playlist.cpp \
		src/gui/cwidgets/playlistview.cpp \
		src/gui/cwidgets/progslider.cpp \
		src/gui/cwidgets/renamepbtn.cpp \
		src/gui/cwidgets/splitter.cpp \
		src/gui/cwidgets/tagview.cpp \
		src/gui/cwidgets/toolbar.cpp \
		src/gui/cwidgets/visualizer.cpp \
		src/gui/cwidgets/volslider.cpp \
		src/gui/dialogs/about.cpp \
		src/gui/dialogs/settings.cpp \
		src/gui/dialogs/tageditor.cpp \
		src/gui/dialogs/transchelper.cpp \
		src/gui/dialogs/transcoder.cpp \
		src/gui/dialogs/wizard.cpp \
		src/gui/helpers/flachelper.cpp \
		src/gui/helpers/intro.cpp \
		src/gui/mwindow.cpp \
		src/gui/workbench.cpp \
		src/library.cpp \
		src/libs/libnotify-qt/Notification.cpp \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp \
		src/player.cpp \
		src/utils/topostfix.cpp \
		src/vars.cpp qrc_package.cpp \
		obj/moc_coverview.cpp \
		obj/moc_dummywidget.cpp \
		obj/moc_libtree.cpp \
		obj/moc_playlist.cpp \
		obj/moc_playlistview.cpp \
		obj/moc_renamepbtn.cpp \
		obj/moc_splitter.cpp \
		obj/moc_tagview.cpp \
		obj/moc_toolbar.cpp \
		obj/moc_transchelper.cpp \
		obj/moc_transcoder.cpp \
		obj/moc_wizard.cpp \
		obj/moc_flachelper.cpp \
		obj/moc_intro.cpp \
		obj/moc_mwindow.cpp \
		obj/moc_library.cpp \
		obj/moc_Notification.cpp \
		obj/moc_OrgFreedesktopNotificationsInterface.cpp \
		obj/moc_player.cpp \
		obj/moc_vars.cpp
OBJECTS       = obj/_main.o \
		obj/coverview.o \
		obj/dummywidget.o \
		obj/libtree.o \
		obj/playlist.o \
		obj/playlistview.o \
		obj/progslider.o \
		obj/renamepbtn.o \
		obj/splitter.o \
		obj/tagview.o \
		obj/toolbar.o \
		obj/visualizer.o \
		obj/volslider.o \
		obj/about.o \
		obj/settings.o \
		obj/tageditor.o \
		obj/transchelper.o \
		obj/transcoder.o \
		obj/wizard.o \
		obj/flachelper.o \
		obj/intro.o \
		obj/mwindow.o \
		obj/workbench.o \
		obj/library.o \
		obj/Notification.o \
		obj/OrgFreedesktopNotificationsInterface.o \
		obj/player.o \
		obj/topostfix.o \
		obj/vars.o \
		obj/qrc_package.o \
		obj/moc_coverview.o \
		obj/moc_dummywidget.o \
		obj/moc_libtree.o \
		obj/moc_playlist.o \
		obj/moc_playlistview.o \
		obj/moc_renamepbtn.o \
		obj/moc_splitter.o \
		obj/moc_tagview.o \
		obj/moc_toolbar.o \
		obj/moc_transchelper.o \
		obj/moc_transcoder.o \
		obj/moc_wizard.o \
		obj/moc_flachelper.o \
		obj/moc_intro.o \
		obj/moc_mwindow.o \
		obj/moc_library.o \
		obj/moc_Notification.o \
		obj/moc_OrgFreedesktopNotificationsInterface.o \
		obj/moc_player.o \
		obj/moc_vars.o
DIST          = LICENSE \
		README.md \
		README.md \
		/ \
		src/libs/libnotify-qt/LICENSE \
		uncrustify.cfg \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/clang.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAsync.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		ocelot.pro src/gui/cwidgets/coverview.hpp \
		src/gui/cwidgets/dummywidget.hpp \
		src/gui/cwidgets/libtree.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/playlistview.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/renamepbtn.hpp \
		src/gui/cwidgets/splitter.hpp \
		src/gui/cwidgets/tagview.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/visualizer.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/wizard.hpp \
		src/gui/helpers/flachelper.hpp \
		src/gui/helpers/intro.hpp \
		src/gui/mwindow.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/player.hpp \
		src/utils/topostfix.hpp \
		src/vars.hpp src/_main.cpp \
		src/gui/cwidgets/coverview.cpp \
		src/gui/cwidgets/dummywidget.cpp \
		src/gui/cwidgets/libtree.cpp \
		src/gui/cwidgets/playlist.cpp \
		src/gui/cwidgets/playlistview.cpp \
		src/gui/cwidgets/progslider.cpp \
		src/gui/cwidgets/renamepbtn.cpp \
		src/gui/cwidgets/splitter.cpp \
		src/gui/cwidgets/tagview.cpp \
		src/gui/cwidgets/toolbar.cpp \
		src/gui/cwidgets/visualizer.cpp \
		src/gui/cwidgets/volslider.cpp \
		src/gui/dialogs/about.cpp \
		src/gui/dialogs/settings.cpp \
		src/gui/dialogs/tageditor.cpp \
		src/gui/dialogs/transchelper.cpp \
		src/gui/dialogs/transcoder.cpp \
		src/gui/dialogs/wizard.cpp \
		src/gui/helpers/flachelper.cpp \
		src/gui/helpers/intro.cpp \
		src/gui/mwindow.cpp \
		src/gui/workbench.cpp \
		src/library.cpp \
		src/libs/libnotify-qt/Notification.cpp \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp \
		src/player.cpp \
		src/utils/topostfix.cpp \
		src/vars.cpp
QMAKE_TARGET  = ocelot
DESTDIR       = bin/
TARGET        = bin/ocelot


first: all
####### Build rules

bin/ocelot:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ocelot.pro /usr/lib/qt/mkspecs/linux-clang/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/clang.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAsync.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCddb.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/dbuscommon.pri \
		/usr/lib/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/qt/mkspecs/features/dbusadaptors.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		ocelot.pro \
		res/package.qrc \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile ocelot.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/clang.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAsync.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KCddb.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_kdav2.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIMAP2.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/qt/mkspecs/modules/qt_KMime.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaCore.pri:
/usr/lib/qt/mkspecs/modules/qt_OktetaGui.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-clang/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt/mkspecs/features/qml_debug.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/dbuscommon.pri:
/usr/lib/qt/mkspecs/features/dbusinterfaces.prf:
/usr/lib/qt/mkspecs/features/dbusadaptors.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
ocelot.pro:
res/package.qrc:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ocelot.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile bin/ocelot

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/package.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/cwidgets/coverview.hpp src/gui/cwidgets/dummywidget.hpp src/gui/cwidgets/libtree.hpp src/gui/cwidgets/playlist.hpp src/gui/cwidgets/playlistview.hpp src/gui/cwidgets/progslider.hpp src/gui/cwidgets/renamepbtn.hpp src/gui/cwidgets/splitter.hpp src/gui/cwidgets/tagview.hpp src/gui/cwidgets/toolbar.hpp src/gui/cwidgets/visualizer.hpp src/gui/cwidgets/volslider.hpp src/gui/dialogs/about.hpp src/gui/dialogs/settings.hpp src/gui/dialogs/tageditor.hpp src/gui/dialogs/transchelper.hpp src/gui/dialogs/transcoder.hpp src/gui/dialogs/wizard.hpp src/gui/helpers/flachelper.hpp src/gui/helpers/intro.hpp src/gui/mwindow.hpp src/gui/workbench.hpp src/library.hpp src/libs/libnotify-qt/Notification.h src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h src/player.hpp src/utils/topostfix.hpp src/vars.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/_main.cpp src/gui/cwidgets/coverview.cpp src/gui/cwidgets/dummywidget.cpp src/gui/cwidgets/libtree.cpp src/gui/cwidgets/playlist.cpp src/gui/cwidgets/playlistview.cpp src/gui/cwidgets/progslider.cpp src/gui/cwidgets/renamepbtn.cpp src/gui/cwidgets/splitter.cpp src/gui/cwidgets/tagview.cpp src/gui/cwidgets/toolbar.cpp src/gui/cwidgets/visualizer.cpp src/gui/cwidgets/volslider.cpp src/gui/dialogs/about.cpp src/gui/dialogs/settings.cpp src/gui/dialogs/tageditor.cpp src/gui/dialogs/transchelper.cpp src/gui/dialogs/transcoder.cpp src/gui/dialogs/wizard.cpp src/gui/helpers/flachelper.cpp src/gui/helpers/intro.cpp src/gui/mwindow.cpp src/gui/workbench.cpp src/library.cpp src/libs/libnotify-qt/Notification.cpp src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp src/player.cpp src/utils/topostfix.cpp src/vars.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_package.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_package.cpp
qrc_package.cpp: res/package.qrc \
		/usr/bin/rcc \
		res/media-playback-pause.svg \
		res/media-playback-start.svg \
		res/next.svg \
		res/gear.svg \
		res/prev.svg \
		res/wrench.png \
		res/media-playback-stop.svg \
		res/configure.svg \
		res/tapeicon.png \
		res/caticon.png
	/usr/bin/rcc -name package res/package.qrc -o qrc_package.cpp

compiler_moc_predefs_make_all: obj/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) obj/moc_predefs.h
obj/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -pthread -Wall -W -dM -E -o obj/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: obj/moc_coverview.cpp obj/moc_dummywidget.cpp obj/moc_libtree.cpp obj/moc_playlist.cpp obj/moc_playlistview.cpp obj/moc_renamepbtn.cpp obj/moc_splitter.cpp obj/moc_tagview.cpp obj/moc_toolbar.cpp obj/moc_transchelper.cpp obj/moc_transcoder.cpp obj/moc_wizard.cpp obj/moc_flachelper.cpp obj/moc_intro.cpp obj/moc_mwindow.cpp obj/moc_library.cpp obj/moc_Notification.cpp obj/moc_OrgFreedesktopNotificationsInterface.cpp obj/moc_player.cpp obj/moc_vars.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_coverview.cpp obj/moc_dummywidget.cpp obj/moc_libtree.cpp obj/moc_playlist.cpp obj/moc_playlistview.cpp obj/moc_renamepbtn.cpp obj/moc_splitter.cpp obj/moc_tagview.cpp obj/moc_toolbar.cpp obj/moc_transchelper.cpp obj/moc_transcoder.cpp obj/moc_wizard.cpp obj/moc_flachelper.cpp obj/moc_intro.cpp obj/moc_mwindow.cpp obj/moc_library.cpp obj/moc_Notification.cpp obj/moc_OrgFreedesktopNotificationsInterface.cpp obj/moc_player.cpp obj/moc_vars.cpp
obj/moc_coverview.cpp: src/gui/cwidgets/coverview.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/coverview.hpp -o obj/moc_coverview.cpp

obj/moc_dummywidget.cpp: src/gui/cwidgets/dummywidget.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/dummywidget.hpp -o obj/moc_dummywidget.cpp

obj/moc_libtree.cpp: src/gui/cwidgets/libtree.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/libtree.hpp -o obj/moc_libtree.cpp

obj/moc_playlist.cpp: src/gui/cwidgets/playlist.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/playlist.hpp -o obj/moc_playlist.cpp

obj/moc_playlistview.cpp: src/gui/cwidgets/playlistview.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlist.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/playlistview.hpp -o obj/moc_playlistview.cpp

obj/moc_renamepbtn.cpp: src/gui/cwidgets/renamepbtn.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/renamepbtn.hpp -o obj/moc_renamepbtn.cpp

obj/moc_splitter.cpp: src/gui/cwidgets/splitter.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/splitter.hpp -o obj/moc_splitter.cpp

obj/moc_tagview.cpp: src/gui/cwidgets/tagview.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/tagview.hpp -o obj/moc_tagview.cpp

obj/moc_toolbar.cpp: src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/player.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/vars.hpp \
		src/library.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/cwidgets/toolbar.hpp -o obj/moc_toolbar.cpp

obj/moc_transchelper.cpp: src/gui/dialogs/transchelper.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/transchelper.hpp -o obj/moc_transchelper.cpp

obj/moc_transcoder.cpp: src/gui/dialogs/transcoder.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/dialogs/transchelper.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/transcoder.hpp -o obj/moc_transcoder.cpp

obj/moc_wizard.cpp: src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/dialogs/wizard.hpp -o obj/moc_wizard.cpp

obj/moc_flachelper.cpp: src/gui/helpers/flachelper.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/helpers/flachelper.hpp -o obj/moc_flachelper.cpp

obj/moc_intro.cpp: src/gui/helpers/intro.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/helpers/intro.hpp -o obj/moc_intro.cpp

obj/moc_mwindow.cpp: src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/gui/mwindow.hpp -o obj/moc_mwindow.cpp

obj/moc_library.cpp: src/library.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/library.hpp -o obj/moc_library.cpp

obj/moc_Notification.cpp: src/libs/libnotify-qt/Notification.h \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/libnotify-qt/Notification.h -o obj/moc_Notification.cpp

obj/moc_OrgFreedesktopNotificationsInterface.cpp: src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h -o obj/moc_OrgFreedesktopNotificationsInterface.cpp

obj/moc_player.cpp: src/player.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/player.hpp -o obj/moc_player.cpp

obj/moc_vars.cpp: src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		obj/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/user/devel/projects/ocelot/obj/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I/home/user/devel/projects/ocelot -I/usr/include/taglib -I/usr/include/Qt5GStreamer -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtDBus -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/lib/clang/8.0.0/include -I/usr/include src/vars.hpp -o obj/moc_vars.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/_main.o: src/_main.cpp src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/_main.o src/_main.cpp

obj/coverview.o: src/gui/cwidgets/coverview.cpp src/gui/cwidgets/coverview.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/coverview.o src/gui/cwidgets/coverview.cpp

obj/dummywidget.o: src/gui/cwidgets/dummywidget.cpp src/gui/cwidgets/dummywidget.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dummywidget.o src/gui/cwidgets/dummywidget.cpp

obj/libtree.o: src/gui/cwidgets/libtree.cpp src/gui/cwidgets/libtree.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/libtree.o src/gui/cwidgets/libtree.cpp

obj/playlist.o: src/gui/cwidgets/playlist.cpp src/gui/cwidgets/playlist.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlistview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/playlist.o src/gui/cwidgets/playlist.cpp

obj/playlistview.o: src/gui/cwidgets/playlistview.cpp src/gui/cwidgets/playlistview.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/renamepbtn.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/playlistview.o src/gui/cwidgets/playlistview.cpp

obj/progslider.o: src/gui/cwidgets/progslider.cpp src/gui/cwidgets/progslider.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/progslider.o src/gui/cwidgets/progslider.cpp

obj/renamepbtn.o: src/gui/cwidgets/renamepbtn.cpp src/gui/cwidgets/renamepbtn.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/renamepbtn.o src/gui/cwidgets/renamepbtn.cpp

obj/splitter.o: src/gui/cwidgets/splitter.cpp src/gui/cwidgets/splitter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/splitter.o src/gui/cwidgets/splitter.cpp

obj/tagview.o: src/gui/cwidgets/tagview.cpp src/gui/cwidgets/tagview.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tagview.o src/gui/cwidgets/tagview.cpp

obj/toolbar.o: src/gui/cwidgets/toolbar.cpp src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/player.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/toolbar.o src/gui/cwidgets/toolbar.cpp

obj/visualizer.o: src/gui/cwidgets/visualizer.cpp src/gui/cwidgets/visualizer.hpp \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/visualizer.o src/gui/cwidgets/visualizer.cpp

obj/volslider.o: src/gui/cwidgets/volslider.cpp src/gui/cwidgets/volslider.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/volslider.o src/gui/cwidgets/volslider.cpp

obj/about.o: src/gui/dialogs/about.cpp src/gui/dialogs/about.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/about.o src/gui/dialogs/about.cpp

obj/settings.o: src/gui/dialogs/settings.cpp src/gui/dialogs/settings.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settings.o src/gui/dialogs/settings.cpp

obj/tageditor.o: src/gui/dialogs/tageditor.cpp src/gui/dialogs/tageditor.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tageditor.o src/gui/dialogs/tageditor.cpp

obj/transchelper.o: src/gui/dialogs/transchelper.cpp src/gui/dialogs/transchelper.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/helpers/flachelper.hpp \
		src/gui/helpers/intro.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/transchelper.o src/gui/dialogs/transchelper.cpp

obj/transcoder.o: src/gui/dialogs/transcoder.cpp src/gui/dialogs/transcoder.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/transcoder.o src/gui/dialogs/transcoder.cpp

obj/wizard.o: src/gui/dialogs/wizard.cpp src/gui/dialogs/wizard.hpp \
		src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wizard.o src/gui/dialogs/wizard.cpp

obj/flachelper.o: src/gui/helpers/flachelper.cpp src/gui/helpers/flachelper.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/flachelper.o src/gui/helpers/flachelper.cpp

obj/intro.o: src/gui/helpers/intro.cpp src/gui/helpers/intro.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/intro.o src/gui/helpers/intro.cpp

obj/mwindow.o: src/gui/mwindow.cpp src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mwindow.o src/gui/mwindow.cpp

obj/workbench.o: src/gui/workbench.cpp src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/player.hpp \
		src/utils/topostfix.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp \
		src/gui/cwidgets/coverview.hpp \
		src/gui/cwidgets/dummywidget.hpp \
		src/gui/cwidgets/libtree.hpp \
		src/gui/cwidgets/playlistview.hpp \
		src/gui/cwidgets/playlist.hpp \
		src/gui/cwidgets/splitter.hpp \
		src/gui/cwidgets/tagview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/workbench.o src/gui/workbench.cpp

obj/library.o: src/library.cpp src/library.hpp \
		src/vars.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/library.o src/library.cpp

obj/Notification.o: src/libs/libnotify-qt/Notification.cpp src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Notification.o src/libs/libnotify-qt/Notification.cpp

obj/OrgFreedesktopNotificationsInterface.o: src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OrgFreedesktopNotificationsInterface.o src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.cpp

obj/player.o: src/player.cpp src/player.hpp \
		src/gui/mwindow.hpp \
		src/libs/libnotify-qt/Notification.h \
		src/libs/libnotify-qt/OrgFreedesktopNotificationsInterface.h \
		src/gui/workbench.hpp \
		src/library.hpp \
		src/vars.hpp \
		src/gui/dialogs/about.hpp \
		src/gui/dialogs/settings.hpp \
		src/gui/dialogs/tageditor.hpp \
		src/gui/dialogs/transcoder.hpp \
		src/gui/dialogs/transchelper.hpp \
		src/gui/cwidgets/progslider.hpp \
		src/gui/cwidgets/toolbar.hpp \
		src/gui/cwidgets/volslider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/player.o src/player.cpp

obj/topostfix.o: src/utils/topostfix.cpp src/utils/topostfix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/topostfix.o src/utils/topostfix.cpp

obj/vars.o: src/vars.cpp src/vars.hpp \
		src/library.hpp \
		src/player.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vars.o src/vars.cpp

obj/qrc_package.o: qrc_package.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_package.o qrc_package.cpp

obj/moc_coverview.o: obj/moc_coverview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_coverview.o obj/moc_coverview.cpp

obj/moc_dummywidget.o: obj/moc_dummywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dummywidget.o obj/moc_dummywidget.cpp

obj/moc_libtree.o: obj/moc_libtree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_libtree.o obj/moc_libtree.cpp

obj/moc_playlist.o: obj/moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_playlist.o obj/moc_playlist.cpp

obj/moc_playlistview.o: obj/moc_playlistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_playlistview.o obj/moc_playlistview.cpp

obj/moc_renamepbtn.o: obj/moc_renamepbtn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_renamepbtn.o obj/moc_renamepbtn.cpp

obj/moc_splitter.o: obj/moc_splitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_splitter.o obj/moc_splitter.cpp

obj/moc_tagview.o: obj/moc_tagview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tagview.o obj/moc_tagview.cpp

obj/moc_toolbar.o: obj/moc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_toolbar.o obj/moc_toolbar.cpp

obj/moc_transchelper.o: obj/moc_transchelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_transchelper.o obj/moc_transchelper.cpp

obj/moc_transcoder.o: obj/moc_transcoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_transcoder.o obj/moc_transcoder.cpp

obj/moc_wizard.o: obj/moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wizard.o obj/moc_wizard.cpp

obj/moc_flachelper.o: obj/moc_flachelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_flachelper.o obj/moc_flachelper.cpp

obj/moc_intro.o: obj/moc_intro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_intro.o obj/moc_intro.cpp

obj/moc_mwindow.o: obj/moc_mwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mwindow.o obj/moc_mwindow.cpp

obj/moc_library.o: obj/moc_library.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_library.o obj/moc_library.cpp

obj/moc_Notification.o: obj/moc_Notification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Notification.o obj/moc_Notification.cpp

obj/moc_OrgFreedesktopNotificationsInterface.o: obj/moc_OrgFreedesktopNotificationsInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_OrgFreedesktopNotificationsInterface.o obj/moc_OrgFreedesktopNotificationsInterface.cpp

obj/moc_player.o: obj/moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_player.o obj/moc_player.cpp

obj/moc_vars.o: obj/moc_vars.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vars.o obj/moc_vars.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

